Spring:
  profiles:
    active: ribon,db
feign:
  hystrix:
    enabled: true
server:
  port: 31004
spring:
  freemarker:
    suffix: .ftl
    charset: UTF-8
    settings:
      classic_compatible: true