spring:
  application:
    name: spring-cloud-eureka-Server
eureka:
  client:
    fetch-registry: true #是否需要从服务端获取注册信息
    register-with-eureka: true  #是否注册到当前服务
    service-url:
      #注册中心高可用模式配置
      defaultZone: http://eurekaServer2:31002/eureka/,http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: eurekaServer1 #当前服务的主机名
    instance-id: http://${eureka.instance.hostname}:${server.port}/eureka/   #当前注册中心服务的唯一id
  server:
    enable-self-preservation: false  #关闭eureka的自我保护机制，eureka的自我保护机制，默认开启
server:
  port: 31001