server:
  port: 31005
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      label: master   #从哪个分支上拉取配置文件，指定分支的名称
      server:
        git:
          uri: https://github.com/lxb-9716/springCloud_maven_NewDemo # 远程git地址
          search-paths: config-resp  #指定从哪个路径下开始搜索
eureka:
  client:
    fetch-registry: true #是否需要从服务端获取注册信息
    register-with-eureka: true  #是否在注册中心进行注册
    serviceUrl:
      defaultZone: http://eurekaServer1:31001/eureka/,http://eurekaServer2:31002/eureka/    #注册中心的集群配置
  instance:
    hostname: localhost #当前服务的主机名
    instanceId: http://${eureka.instance.hostname}:${server.port}/eureka/   #当前注册中心服务的唯一id